### ISSUE TITLE
Ikuu Fan Controller - no light control via flows

### ISSUE THREAD

**Issue by skarotech** [gslender/com.gslender.mercator#1]
Hi,
I have a few Ikuu Fan controller, and while they add fine, and have light control via the tile, there is no such control in flows like the other ikuu devices, for controlling the light, only Fan - can this be added
<img width="1203" alt="Screenshot 2024-10-10 at 8 09 07 pm" src="https://github.com/user-attachments/assets/8d374301-9bc4-4a4b-a266-eb58d3cdaf14">
<img width="502" alt="Screenshot 2024-10-10 at 8 10 07 pm" src="https://github.com/user-attachments/assets/f99c6683-c560-489d-9f3c-bc00e164cea9">.

also related, there are no 'AND' actions in flows, to check the state, eg on/off etc

happy to provide any additional info and testing, or send you one if needed to test/develop.

**Comment by gslender** [comment]
Correct. The flows don't exist correctly because the Capabilities are custom and I haven't created them. 

I'm thinking I might change the way this device works and remove the fan on/off and just leave the light. The fan enum will be the only way to turn on/off along withe speed.

**Comment by skarotech** [comment]
thanks, let me know when I can test.

I also have an Ikuu Rotary Dimmer which is not listed, would be great if we can add this at some point.

**Comment by skarotech** [comment]
hi, just spotted the updated test app, have installed and can confirm

- light control via flows (THEN) working
- light status via flows (AND) working

- fan control via tile working
- fan control via flows NOT working, gives error
<img width="562" alt="Screenshot 2024-10-13 at 1 53 56 pm" src="https://github.com/user-attachments/assets/c2a5c99b-da7a-4ab2-ad32-7b38616b14b4">

**Comment by gslender** [comment]
Test v1.1.12 has it fixed
