### ISSUE TITLE
Twin Light Switch Showing as Generic Zigbee Device

### ISSUE THREAD

**Issue by Marko9au** [gslender/com.gslender.mercator#3]
When adding a new Twin Light Switch using the Ikuu app the device is added as a generic Zigbee device.

The new device operates as a single switch, turning both loads on and off simultaneously.

The new device is showing the following:

   Manufacturer ID:  _TZ3000_fbjdkph9
   Product ID:   TS0002

Can the app be updated show that the device shows correctly as two independent switches?

Thanks.

**Comment by gslender** [comment]
No

**Comment by Marko9au** [comment]
Hey @gslender , Just to confirm, there's no future development planned for the Ikuu app?

**Comment by gslender** [comment]
No, development will continue. I'm just not in agreement with your request.

**Comment by Marko9au** [comment]
That great news. I really like the app.

I looked through the code, as best as I'm able as I'm not a developer, and it looks to me that my request(s) would be very similar to the changes made in update 1.1.7 where additional Manufacturer IDs were added for various device types.

I don't want to oversimplify the ask, and I assume I am probably missing something, but is there additional complexity to resolve the issue I've shared?

I suspect I've made a hash of the issue, making it more confusing than need be.

Thanks.

**Comment by gslender** [comment]
Sorry, if all you are asking for is to have "_TZ3000_fbjdkph9" included in the list of manufacturerName, then that's okay and I've added that ready for the next update.

**Comment by Marko9au** [comment]
Thank you @gslender , are you able to do the same for the Double Power Point request?

**Comment by Marko9au** [comment]
Downloaded the version 1.1.13 (test) and the twin light switch installed correctly.  Thank you for the update.
