### ISSUE TITLE
Double Power Point showing as Generic Zigbee Device

### ISSUE THREAD

**Issue by Marko9au** [gslender/com.gslender.mercator#4]
When adding a new Double Power Point using the Ikuu app the device is added as a generic Zigbee device.

The new device operates as a single switch, functioning only on the left socket.

The new device is showing the following:

Manufacturer ID: _TZ3210_raqjcxo5
Product ID: TS011F

Can the app be updated show that the device shows correctly as two independent power sockets?

Thanks.

**Comment by gslender** [comment]
No

**Comment by gslender** [comment]
Implemented the _TZ3210_raqjcxo5 manufacturerName

**Comment by Marko9au** [comment]
Thank you, is there an ETA for the next release of the App?

**Comment by Marko9au** [comment]
Downloaded the version 1.1.13 (test) and the double power point installed correctly.  Thank you for the update.
